Working home but the UI changes are not visible
krish7777/food4all pull request #44
Opened 2020-10-29 11:26 UTC by arpit1912

@sam3926  just take a look and let me know what changes I should make.

2020-10-29 16:10 UTC, sam3926 commented
@arpit1912 home left side pane collapsible doesn't seem to be working. Also on clicking your profile in left home pane, the profile page should open. In posts, the bottom buttons only work if you click directly on button and not nearby even though mouse pointer turns clickable. Also like button should change on clicking (@dinkar64  can help you with last two things)

2020-10-29 16:14 UTC, sam3926 commented
also @arpit1912 edit post template to keep only date at right side (for now there are two components there with a break statement even though only one date needs to be displayed). Posts in profile section also needs to be connected and edited to be same template

2020-10-29 16:37 UTC, sam3926 requested changes

2020-10-29 16:37 UTC, sam3926 commented on frontend/src/components/HomeCenter/index.js
> +                    <Card title={post.author} extra={<p>{post.DateTime}</p>} style={{ width: 700 , margin:"8px"}}
@arpit1912  Remove paragraph tag here

2020-10-29 17:29 UTC, arpit1912 commented
@sam3926 I have made the changes in the home pages check it out once.

2020-10-30 06:53 UTC, sam3926 commented
@arpit posts look fine now, just gotta settle the dates issue
Home page work left:
1. link left pane profile vie to self profile page
2. make left pane collapsible working
3. increase button clickable area (make the entire div clickable)

2020-10-30 07:03 UTC, arpit1912 commented
The date issue is resolved..try to create new post, the date is in the required format.. if not coming maybe I will push it into the next pr as it's there in my local branch

2020-10-30 07:08 UTC, sam3926 commented
Cool
@arpit1912 i've edited the profile post layout to match home one, link it to the backend

2020-10-30 20:05 UTC, arpit1912 commented
@sam3926  @dinkar64  @krish7777  checkout the working donation section of the discover page meanwhile I will request you guys to create some post as I need it for checking of filters do check the update in the expiry date picker as well :smile:

2020-10-30 20:06 UTC, arpit1912 commented
> Cool
> @arpit1912 i've edited the profile post layout to match home one, link it to the backend
 Sure! I thought you merged this branch so committed here.. anyways try to close it asap...Will do your work In the next PR

2020-10-30 21:07 UTC, arpit1912 commented
@dinkar64  now the interest and reject buttons on discover and profile page are working as well as changing the database in real time

2020-10-31 06:14 UTC, merged